apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  # local:
  #   push: false
  #   useDockerCLI: true
  googleCloudBuild:
    projectId: ticketing-dev-279703
  artifacts:
    - image: us.gcr.io/ticketing-dev-279703/auth
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.auth
      sync:
        manual:
          - src: "packages/auth/src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-279703/client
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.client
      sync:
        manual:
          - src: "packages/client/**/*.tsx"
            dest: .
    - image: us.gcr.io/ticketing-dev-279703/tickets
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.tickets
      sync:
        manual:
          - src: "packages/tickets/**/*.tsx"
            dest: .
