apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: dereegz/auth
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.auth
      sync:
        manual:
          - src: "packages/auth/src/**/*.ts"
            dest: .
    - image: dereegz/client
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.client
      sync:
        manual:
          - src: "packages/client/**/*.tsx"
            dest: .
    - image: dereegz/tickets
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.tickets
      sync:
        manual:
          - src: "packages/tickets/**/*.ts"
            dest: .
    - image: dereegz/orders
      context: .
      docker:
        dockerfile: ./infrastructure/docker/Dockerfile.orders
      sync:
        manual:
          - src: "packages/orders/**/*.ts"
            dest: .
