FROM node:alpine

WORKDIR /app

COPY package.json .
COPY packages/auth/package.json ./packages/auth/package.json
COPY packages/backend-core ./packages/backend-core

RUN yarn install --only=prod

COPY packages/auth ./packages/auth

CMD ["yarn", "workspace", "@ticketing/auth", "start"]
