FROM node:alpine

WORKDIR /app

COPY package.json .
COPY packages/tickets/package.json ./packages/tickets/package.json
COPY packages/backend-core ./packages/backend-core

RUN yarn install --only=prod

COPY packages/tickets ./packages/tickets

CMD ["yarn", "workspace", "@ticketing/tickets", "start"]
